import { useEffect, useState } from 'react'
import { api } from '../api'

export default function RMConsole() {
  const [leads, setLeads] = useState([])

  useEffect(() => {
    api.leads().then(setLeads).catch(() => {})
    const t = setInterval(() => api.leads().then(setLeads).catch(() => {}), 4000)
    return () => clearInterval(t)
  }, [])

  return (
    <div className="dash">
      <div className="card">
        <div className="card-title">🏦 RM Lead Console <span className="pill live">LIVE</span></div>
        <p className="muted small">Qualified leads generated by Saarthi's Compliance &amp; Suitability Gate — regulated products are routed here instead of AI advice.</p>
        {leads.length === 0 && (
          <div className="empty-state small">
            No leads yet. Ask Saarthi about <i>term insurance</i> or <i>PMS</i> as a customer — the compliance gate will route it here.
          </div>
        )}
        {leads.map((l) => (
          <div key={l.id} className={`lead-row ${l.priority === 'HIGH' ? 'high' : ''}`}>
            <div className="lead-row-head">
              <b>{l.customer_name}</b>
              <span className={`pill ${l.priority === 'HIGH' ? 'hot' : ''}`}>{l.priority}</span>
            </div>
            <div className="lead-product">{l.product}{l.household ? ' · household query' : ''}</div>
            <div className="lead-context">{l.context}</div>
            <div className="lead-meta">{l.id} · {l.segment} · {l.created} · {l.status}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
